#!/usr/bin/env python3


def build(bld):
    if not bld.env.HAS_GTEST:
        return

    features = ['test'] if bld.cmd == 'check' else []
    bld.ap_program(
        features=features,
        includes=['..', bld.srcnode.abspath() + '/tests/'],
        source=[
            'test_vektor_protocol.cpp',
            '../Vektor_Protocol.cpp',
            '../Vektor_AssignmentMatrix.cpp',
            '../Vektor_Capability.cpp',
            '../Vektor_PwmInput.cpp',
            '../Vektor_PwmOutput.cpp',
            '../Vektor_Rcin.cpp',
            '../Vektor_RequestCache.cpp',
            '../Vektor_Runtime.cpp',
            '../Vektor_Schema.cpp',
            '../Vektor_SerialProtocol.cpp',
            '../Vektor_Subscription.cpp',
            '../Vektor_Vsp.cpp',
        ],
        use=['ap', 'GTEST'],
        program_name='test_vektor_protocol',
        program_groups='tests',
        use_legacy_defines=False,
        vehicle_binary=False,
        cxxflags=['-Wno-undef'],
    )
